"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REFLECT_CONTROL = Symbol("__control__");
exports.REFLECT_SERVICE = Symbol("__service__");
exports.REFLECT_IMPORT = Symbol("__import__");
exports.REFLECT_PATH = Symbol("__path__");
exports.REFLECT_METHOD = Symbol("__method__");
exports.REFLECT_PARAM = Symbol("__param__");
exports.REFLECT_MIDDLEWARE = Symbol("__middleware__");
exports.REFLECT_CLASS_TYPE = Symbol("__type:class");
exports.REFLECT_CLASS_CONTROL_TYPE = "control";
exports.REFLECT_CLASS_SERVICE_TYPE = "service";
exports.REFLECT_CLASS_MODULE_TYPE = "module";
exports.REFLECT_INJECTS = "inject";
